#!/usr/bin/env -S uv run


import datetime
import io
from typing import final
import argparse


def md_link(text: str, url: str) -> str:
    return f"[{text}]({url})"


def notes_link(title: str, text: str = "notes"):
    return f"{md_link(text, f'./notes/{title}.md')}"


@final
class TableRow:
    def __init__(
        self,
        num: int | None,
        date: datetime.date,
        lecture: str,
        reading: str,
        comment: str,
    ):
        self.num = num
        self.date = date
        self.lecture = lecture
        self.reading = reading
        self.comment = comment

    def render(self):
        # date format like Thu Sep 4
        num = f"{self.num:2}" if self.num else "  "
        return f"| {num} | {self.date.strftime('%a %b %-d')} | {self.lecture} | {self.reading} | {self.comment} |"


@final
class Lecture:
    def __init__(
        self, title: str, notes: str, has_slides: bool = False, comment: str = ""
    ):
        self.title = title
        self.notes = notes
        self.has_slides = has_slides
        self.comment = comment

    def row(self, num: int, date: datetime.date) -> TableRow:
        lecture = self.title
        if self.has_slides:
            slides_url = f"./slides/lec{num}.pdf"
            lecture = f"{self.title}: {md_link('slides', slides_url)}"
        return TableRow(num, date, lecture, self.notes, self.comment)


@final
class NoClass:
    def __init__(self, reason: str, date: datetime.date):
        self.reason = reason
        self.date = date

    def row(self, date: datetime.date) -> TableRow:
        if self.date != date:
            expected = self.date.strftime("%a %b %d")
            actual = date.strftime("%a %b %d")
            raise ValueError(
                f"NoClass {self.reason} should be on {expected} but was placed at {actual}"
            )
        return TableRow(
            None, date, f"**No class** ({self.reason})", reading="", comment=""
        )


@final
class AssignmentDue:
    def __init__(self, title: str, url: str, date: datetime.date):
        self.title = title
        self.url = url
        self.date = date

    def row(self):
        link = md_link(f"{self.title}", self.url)
        return TableRow(
            None, self.date, lecture="", reading="", comment=f"_{link} due (11pm)_"
        )


def next_date(date: datetime.date, weekdays: list[int]):
    date += datetime.timedelta(days=1)
    while date.weekday() not in weekdays:
        date += datetime.timedelta(days=1)
    return date


def to_calendar(
    entries: list[Lecture | NoClass | AssignmentDue], start_date: datetime.date
) -> str:
    buffer = io.StringIO()
    date = start_date
    # decide if tue/thu or mon/wed based on first day
    weekdays = [1, 3] if start_date.weekday() in [1, 3] else [0, 2]
    lec_num = 1

    print("<!-- AUTO-GENERATED BY mk-cal.py -->", file=buffer)
    print("<!-- markdownlint-disable MD041 -->", file=buffer)
    print("| | Date | Lecture | Reading | |", file=buffer)
    print("| --- | :-- | --- | --- | --- |", file=buffer)
    for e in entries:
        row: TableRow | None = None
        if isinstance(e, Lecture):
            row = e.row(lec_num, date)
            date = next_date(date, weekdays)
            lec_num += 1
        if isinstance(e, NoClass):
            row = e.row(date)
            date = next_date(date, weekdays)
        if isinstance(e, AssignmentDue):
            if not (e.date <= date):
                raise ValueError(
                    f"{e.title} due date {e.date} should be before next lecture on {date}"
                )
            row = e.row()
        if row:
            print(row.render(), file=buffer)
    return buffer.getvalue()


class_start_date: datetime.date = datetime.date(2025, 9, 4)
entries: list[Lecture | AssignmentDue | NoClass] = [
    Lecture("Introduction", notes_link("overview"), has_slides=True, comment=""),
    Lecture(
        "Rocq introduction",
        f"{notes_link('rocq_intro')}, " + f"{md_link('syllabus', './syllabus.md')}",
        has_slides=True,
        comment=f"bring a laptop and follow {md_link('setup', './assignments/setup.md')}",
    ),
    Lecture("Induction", notes_link("induction"), has_slides=True, comment=""),
    Lecture("Abstraction", notes_link("adt_specs"), has_slides=True, comment=""),
    Lecture(
        "Hoare logic (part 1)",
        notes_link("hoare"),
        has_slides=True,
        comment="theory lecture",
    ),
    Lecture(
        "Hoare logic (part 2)",
        notes_link("hoare", text="same notes"),
        has_slides=True,
        comment="theory lecture",
    ),
    Lecture(
        "Separation logic (part 1)",
        notes_link("sep-logic"),
        has_slides=True,
        comment="theory lecture",
    ),
    AssignmentDue("Assignment 1", "./assignments/hw1/", datetime.date(2025, 9, 29)),
    Lecture(
        "Separation logic (part 2)",
        notes_link("sep-logic", text="same notes"),
        has_slides=True,
        comment="theory lecture",
    ),
    NoClass("Tej is traveling", datetime.date(2025, 10, 2)),
    Lecture(
        "Iris Proof Mode (part 1)",
        notes_link("ipm"),
        comment="bring a laptop",
    ),
    NoClass("Tej is sick", datetime.date(2025, 10, 9)),
    Lecture(
        "Iris Proof Mode (part 2)",
        notes_link("ipm", text="same notes"),
        comment="bring a laptop",
    ),
    Lecture("Modeling Go programs", notes_link("goose"), has_slides=True),
    AssignmentDue("Assignment 2", "./assignments/hw2/", datetime.date(2025, 10, 20)),
    Lecture("Ownership (part 1)", notes_link("ownership"), comment="bring a laptop"),
    Lecture(
        "Ownership (part 2)",
        notes_link("ownership", text="same notes"),
        comment="bring a laptop",
    ),
    Lecture("Loop invariants (part 1)", notes_link("loop_invariants")),
    Lecture(
        "Loop invariants (part 2)", notes_link("loop_invariants", text="same notes")
    ),
    Lecture("Persistence", notes_link("persistently")),
    Lecture("Concurrency intro", notes_link("concurrency")),
    Lecture("Lock invariants", notes_link("invariants")),
    Lecture("Ghost state", notes_link("ghost_state")),
    Lecture("Atomic specs", notes_link("atomic_specs")),
    AssignmentDue("Assignment 3", "./assignments/hw3/", datetime.date(2025, 11, 17)),
    Lecture("Barrier proof (spec)", notes_link("barrier")),
    Lecture("Barrier proof", ""),
    NoClass("Thanksgiving", datetime.date(2025, 11, 27)),
    Lecture("Property-based testing", notes_link("pbt")),
    Lecture("Liveness", notes_link("liveness")),
    Lecture("Course wrap-up", notes_link("summary")),
    AssignmentDue("Assignment 4", "./assignments/hw4/", datetime.date(2025, 12, 11)),
]

# Had a week off for SOSP in Fall 2024.
# Fall 2025 has fewer lecture days.
# Fall 2025 had one travel day for NESVD and one sick day.
# Dropped lectures: Resource algebras, ADT invariants, and SMT


def main():
    parser = argparse.ArgumentParser()
    _ = parser.add_argument("output", type=argparse.FileType("w"))
    args = parser.parse_args()
    print(
        to_calendar(entries, start_date=class_start_date),
        end="",
        file=args.output,
    )


if __name__ == "__main__":
    main()
